"""default role

Revision ID: e337512e24f9
Revises: 0d4e7051a13c
Create Date: 2025-05-05 14:00:46.714368

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e337512e24f9'
down_revision: Union[str, None] = '0d4e7051a13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'evaluation', 'participant', ['judge_id'], ['id'])
    op.create_foreign_key(None, 'evaluation', 'submission', ['submission_id'], ['id'])
    op.create_foreign_key(None, 'submission', 'team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'submission', 'challenge', ['challenge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    # ### end Alembic commands ###
